  	#ifndef NETMAP_LINUX_CONFIG_H
  	#define NETMAP_LINUX_CONFIG_H

		#define NETMAP_LINUX_I40E_PTR_STATE 

		#define NETMAP_LINUX_I40E_PTR_ARRAY 

		#define NETMAP_LINUX_VIRTIO_NOTIFY 

		#define NETMAP_LINUX_VIRTIO_MULTI_QUEUE 

		#define NETMAP_LINUX_VIRTIO_FUNCTIONS 

		#define NETMAP_LINUX_VIRTIO_FREE_PAGES 

		#define NETMAP_LINUX_VIRTIO_GET_VRSIZE 

		#define NETMAP_LINUX_VIRTIO_CB_DELAYED 

		#define NETMAP_LINUX_IXGBEVF_PTR_ARRAY 

		#define NETMAP_LINUX_IXGBE_PTR_ARRAY 

		#define NETMAP_LINUX_IXGBE_DESC 3

		#define NETMAP_LINUX_HAVE_E1000E_EXT_RXDESC 

		#define NETMAP_LINUX_HAVE_E1000E_DOWN2 

		#define NETMAP_LINUX_HAVE_PCI_ENABLE_MSIX 

		#define NETMAP_LINUX_HAVE_NETDEV_DTOR 

		#define NETMAP_LINUX_HAVE_NONVOID_GET_STATS64 

		#define NETMAP_LINUX_HAVE_FAULT_VMA_ARG 

		#define NETMAP_LINUX_PAGE_COUNT _count

		#define NETMAP_LINUX_HAVE_SKB_CHECKSUM_START_OFFSET 

		#define NETMAP_LINUX_HAVE_SKB_FRAG_ADDRESS 

		#define NETMAP_LINUX_HAVE_SKB_FRAG_SIZE 

		#define NETMAP_LINUX_SKB_ADD_RX_FRAG_6ARGS 

		#define NETMAP_LINUX_HAVE_XMIT_MORE 

		#define NETMAP_LINUX_HAVE_ALLOC_SKB_IP_ALIGN 

		#define NETMAP_LINUX_HAVE_NAPI_ALLOC_SKB 

		#define NETMAP_LINUX_HAVE_NAPI_COMPLETE_DONE 

		#define NETMAP_LINUX_QDISC_CREATE_DFLT_3ARGS 

		#define NETMAP_LINUX_HAVE_NNITD 

		#define NETMAP_LINUX_ALLOC_NETDEV_4ARGS 

		#define NETMAP_LINUX_HAVE_ADDR_RANDOM 

		#define NETMAP_LINUX_HAVE_HW_FEATURES 

		#define NETMAP_LINUX_HAVE_TX_SKB_SHARING 

		#define NETMAP_LINUX_HAVE_GET_STATS64 

		#define NETMAP_LINUX_HAVE_LIVE_ADDR_CHANGE 

		#define NETMAP_LINUX_HAVE_HRTIMER_MODE_REL 

		#define NETMAP_LINUX_HAVE_USLEEP_RANGE 

		#define NETMAP_LINUX_HAVE_NETDEV_TX_T 

		#define NETMAP_LINUX_HAVE_NETDEV_OPS 

		#define NETMAP_LINUX_HAVE_PHYS_ADDR_T 

		#define NETMAP_LINUX_HAVE_HRTIMER_FORWARD_NOW 

		#define NETMAP_LINUX_HAVE_QUEUE_MAPPING 

		#define NETMAP_LINUX_HAVE_UINTPTR 

		#define NETMAP_LINUX_HAVE_SKB_COPY_LINEAR 

		#define NETMAP_LINUX_HAVE_INIT_NET 

		#define NETMAP_LINUX_HAVE_UNLOCKED_IOCTL 

		#define NETMAP_LINUX_PWAIT_KEY _key

		#define NETMAP_LINUX_HAVE_SET_REAL_NUM_TX_QUEUES 

		#define NETMAP_LINUX_HAVE_NUM_RX_QUEUES 

		#define NETMAP_LINUX_HAVE_REAL_NUM_RX_QUEUES 

		#define NETMAP_LINUX_HAVE_PERNET_OPS_ID 

		#define NETMAP_LINUX_HAVE_SET_CHANNELS 

		#define NETMAP_LINUX_HAVE_GET_RINGPARAM 

		#define NETMAP_LINUX_SELECT_QUEUE 4

		#define NETMAP_LINUX_HAVE_RX_HANDLER_RESULT 

		#define NETMAP_LINUX_HAVE_RX_REGISTER 

		#define NETMAP_LINUX_TIMER_RTYPE enum hrtimer_restart

		#define NETMAP_LINUX_HAVE_IOMMU 

		#define NETMAP_LINUX_HAVE_SPLIT_PAGE 

		#define NETMAP_LINUX_DRIVER_SUFFIX ""
  
  	#endif
